### ISSUE TITLE
feature request: smaller dependencies

### ISSUE THREAD

**Issue by Pomax** [k33g/gh3#20]
Being dependent on jQuery and underscore for this library adds a hell of a lot of weight to just being able to talk to the github API - it's going to be worth looking at what you actually use from both, and ideally shimming that if jquery and/or underscore are not available. Compared to the huge size of both, the shim is likely tiny, but immensely valuable in settings where neither is loaded.

**Comment by k33g** [comment]
yes you're right, I'm thinking about this

**Comment by k33g** [comment]
I've started something with traceur [https://github.com/k33g/gh3.next](https://github.com/k33g/gh3.next)
