### ISSUE TITLE
User Profile Picture Option?

### ISSUE THREAD

**Issue by iheartkode** [k33g/gh3#23]
I was looking in the readme and did not find anything, is it possible to add this? Or if it's hidden can you show it on the README : +1:

**Comment by leivaburto** [comment]
If you open the user example on the samples folder (samples/01-user.html), you'll see that you can get the user profile picture by accessing **avatar_url** property on the user object, namely k33g.avatar_url

**Comment by k33g** [comment]
:+1:

**Comment by iheartkode** [comment]
Thanks
