### ISSUE TITLE
Added support for commit comments

### ISSUE THREAD

**Issue by leivaburto** [k33g/gh3#24]
Hello,

I've been playing with gh3 and, based on what is done (Gists comments), [I added support for fetching commit comments](https://github.com/leivaburto/gh3/commit/5b261609b5d10267fd0b69d7762bf3624e366e05). A couple of things to notice:

1) I had a problem fetching commits for a file when the author's login (of the commit) was null, namely when an user changed his github username. In that case, the [commitInfos.author]( https://github.com/k33g/gh3/blob/master/gh3.js#L482) was null but commitInfos.commit.author was good, so I modified that on [my commit](https://github.com/leivaburto/gh3/commit/5b261609b5d10267fd0b69d7762bf3624e366e05).

2) Github API [allows specifying the format of the data to receive](https://developer.github.com/v3/media/). In the case of fetching commit comments, I added the option to receive the full content, which means it will receive not just the comment body (raw) but also body_text (plain text) and body_html (markdown rendered in HTML).

Finally, [I added an example to samples folder](https://github.com/leivaburto/gh3/blob/master/samples/14-commit_comments.html) in order to show how to get comments from a file commit. The example is based on the ["real world" use of that functionality](https://leivaburto.github.io/2015/02/12/hello-world/).
Ex. screenshot:
![gh3](https://cloud.githubusercontent.com/assets/1937074/6197201/6d207872-b3c0-11e4-93e4-0e0636dbe39f.png)

If everything is OK I could do a pull-request. Let me know.

**Comment by k33g** [comment]
@leivaburto nice! go! :+1:
